// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.Internalball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2;

		public static void Serialize(ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2 Deserialize(IInProtocolBitStream bitStream)
		{

			return new ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2
			(
			){};
		}
	}
}
