// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct breakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input : IEntityInput
	{
		public uint GetComponentType() => Definition.Internalbreakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input;

		private readonly bool isRemoteInput;

		public breakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(breakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static breakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input Deserialize(IInProtocolBitStream bitStream)
		{

			return new breakout_pieces_78_a5e9c6619f64a0a41ada7af541fac44b_Input
			(
				true
			);
		}
	}
}
