// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_a3a3c71b4ac349e438defc94ab13ef46_63ca1186_585d_453e_afd3_cbc2fc7a1727 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}


	[Preserve]
	public class CoherenceSyncball_a3a3c71b4ac349e438defc94ab13ef46 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncball_a3a3c71b4ac349e438defc94ab13ef46>();

		// Cached targets for commands		
		private global::ScriptForRealBall ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["63ca1186-585d-453e-afd3-cbc2fc7a1727"] = new Binding_a3a3c71b4ac349e438defc94ab13ef46_63ca1186_585d_453e_afd3_cbc2fc7a1727(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncball_a3a3c71b4ac349e438defc94ab13ef46()
		{
			bakedCommandBindings.Add("ad42c870-f2cc-4844-bfbf-d48aad054ca2", BakeCommandBinding_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2_CommandTarget = (global::ScriptForRealBall)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("ScriptForRealBall.ChangeStateToGameOver", "()",
				SendCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2, ReceiveLocalCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2, MessageTarget.AuthorityOnly, ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncball_a3a3c71b4ac349e438defc94ab13ef46>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(MessageTarget target, object[] args)
		{
			var command = new ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(MessageTarget target, object[] args)
		{
			var command = new ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2();
			ReceiveCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(command);
		}

		void ReceiveCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2 command)
		{
			var target = ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2_CommandTarget;
			target.ChangeStateToGameOver();
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2 castedCommand:
					ReceiveCommand_ball_a3a3c71b4ac349e438defc94ab13ef46_ScriptForRealBall__char_46_ChangeStateToGameOver_ad42c870_f2cc_4844_bfbf_d48aad054ca2(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncball_a3a3c71b4ac349e438defc94ab13ef46] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
